export const EVENT_FETCH_IMAGE = 'EVENT_FETCH_IMAGE';
export const EVENT_INIT_DATA = 'EVENT_INIT_DATA';
export const EVENT_INIT_BOARD_VIEW = 'EVENT_INIT_BOARD_VIEW';
export const EVENT_UPDATE_PUZZLE_VIEW = 'EVENT_UPDATE_PUZZLE_VIEW';
export const EVENT_UPDATE_HINT_VIEW = 'EVENT_UPDATE_HINT_VIEW'
export const EVENT_TOUCH_PUZZLE = 'EVENT_TOUCH_PUZZLE';
export const EVENT_COMPLETE_PUZZLE = 'EVENT_COMPLETE_PUZZLE';
