export const EVENT_FETCH_ANSWER_IMAGE = 'EVENT_FETCH_ANSWER_IMAGE';
export const EVENT_FETCH_ORIGIN_IMAGE = 'EVENT_FETCH_ORIGIN_IMAGE';
export const EVENT_INIT_DATA = 'EVENT_INIT_DATA';
export const EVENT_INIT_BOARD_VIEW = 'EVENT_INIT_BOARD_VIEW';
export const EVENT_INIT_PUZZLES_VIEW = 'EVENT_INIT_PUZZLES_VIEW';
export const EVENT_UPDATE_PUZZLE_VIEW = 'EVENT_UPDATE_PUZZLE_VIEW';
export const EVENT_UPDATE_HINT_VIEW = 'EVENT_UPDATE_HINT_VIEW'
export const EVENT_UPDATE_BOARD_VIEW_POSITION = 'EVENT_UPDATE_BOARD_VIEW_POSITION';
export const EVENT_START_TOUCH_PUZZLE = 'EVENT_START_TOUCH_PUZZLE';
export const EVENT_END_TOUCH_PUZZLE = 'EVENT_END_TOUCH_PUZZLE';
export const EVENT_UPDATE_TIMER = 'EVENT_UPDATE_TIMER';

export const EVENT_START_PUZZLE = 'EVENT_START_PUZZLE';
export const EVENT_COMPLETE_PUZZLE = 'EVENT_COMPLETE_PUZZLE';

export const EVENT_PLAY_CLEAR = 'EVENT_PLAY_CLEAR';
export const EVENT_PLAY_RESULT = 'EVENT_PLAY_RESULT';
export const EVENT_PLAY_CLEAR_X = 'EVENT_PLAY_CLEAR_X';
export const EVENT_PLAY_COLORIZE = 'EVENT_PLAY_COLORIZE';
export const EVENT_PLAY_CLEAN_BACKGROUND = 'EVENT_PLAY_CLEAN_BACKGROUND';
